name: flutter_pcm_sound
description: Send real-time PCM audio (16-bit integer) to your device speakers
version: 3.1.3
homepage: https://github.com/chipweinberger/flutter_pcm_sound

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  win32: ^5.9.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_pcm_sound
        pluginClass: FlutterPcmSoundPlugin
      ios:
        pluginClass: FlutterPcmSoundPlugin
      macos:
        pluginClass: FlutterPcmSoundPlugin
      windows:
        dartPluginClass: FlutterPcmSoundWindows
      linux:
        pluginClass: FlutterPcmSoundPlugin
      web:
        pluginClass: FlutterPcmSoundPlugin
        fileName: web/flutter_pcm_sound_web.dart

